name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Repo checked out into $GITHUB_WORKSPACE
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log environment variables
        run: |
          echo $HOME
          echo $GITHUB_WORKSPACE
          name=$(basename "$GITHUB_WORKSPACE")
          echo $name

      - name: Install LilyPond
        run: |
          lilypond=/tmp/lilypond
          lilypond_url=http://lilypond.org/download/binaries/linux-64/
          lilypond_source=lilypond-2.21.82-1.linux-64.sh
          wget -q -O $lilypond $lilypond_url/$lilypond_source
          sh $lilypond --batch

      - name: Clone & install Abjad trevor/dev
        run: |
          git clone -b trevor/dev https://github.com/Abjad/abjad.git /tmp/abjad
          pip install -e /tmp/abjad
